HOSTS:
  win-2012R2-std:
    roles:
     - default 
     - agent
    platform: windows-server-amd64
    box : opentable/win-2012r2-standard-amd64-nocm
    box_url : https://atlas.hashicorp.com/opentable/boxes/win-2012r2-standard-amd64-nocm
    hypervisor : vagrant_virtualbox
    user: vagrant
    ip: 192.168.50.4
    is_cygwin: false
    provider: virtualbox
CONFIG:
  log_level: verbose
  type: git